#!/bin/bash
now=$(date +"%Y-%d-%m %H:%M:%S")
USER_HOME=
case "$1" in
    hibernate|suspend)
        echo "out,hibernate,$now" >> $USER_HOME/worktime.csv
        ;;
    thaw|resume)
        #there is some delay before entry will show up
        echo "in,hibernate,$now" >> $USER_HOME/worktime.csv
        ;;
    *)
        ;;
esac
exit $?
