#! /bin/sh
### BEGIN INIT INFO
# Provides:          worktime-start
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Save start worktime
# Description:
### END INIT INFO
now=$(date +"%Y-%d-%m %H:%M:%S")
USER_HOME=
echo "in,power,$now" >> $USER_HOME/worktime.csv
